-- Villes du Togo (référence pour suggestions / filtres)
-- mysql -u root zovu < migration-villes-togo.sql

SET NAMES utf8mb4;

INSERT IGNORE INTO villes (nom) VALUES
('Lomé'),
('Tsévié'),
('Aného'),
('Tabligbo'),
('Vogan'),
('Kévé'),
('Afagnan'),
('Agbodrafo'),
('Aflao'),
('Notsé'),
('Kpalimé'),
('Atakpamé'),
('Badou'),
('Anié'),
('Elavagnon'),
('Amou-Oblo'),
('Blitta'),
('Sokodé'),
('Tchamba'),
('Sotouboua'),
('Bafilo'),
('Kara'),
('Bassar'),
('Niamtougou'),
('Kanté'),
('Pagouda'),
('Kozah'),
('Dapaong'),
('Mango'),
('Cinkassé'),
('Tandjouaré'),
('Gando'),
('Naki-Est'),
('Kpagouda'),
('Vakpo'),
('Kouvé'),
('Tové'),
('Adidogomé'),
('Baguida'),
('Agoè');
