/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PartenariatRouteImport } from './routes/partenariat'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ContributorRouteImport } from './routes/contributor'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConditionsRouteImport } from './routes/conditions'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as EpreuvesIdRouteImport } from './routes/epreuves.$id'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AccountSoumissionsRouteImport } from './routes/account.soumissions'
import { Route as AccountProfilRouteImport } from './routes/account.profil'
import { Route as AccountPortefeuilleRouteImport } from './routes/account.portefeuille'
import { Route as AccountFavorisRouteImport } from './routes/account.favoris'
import { Route as AccountBibliothequeRouteImport } from './routes/account.bibliotheque'
import { Route as AccountSoumissionsIdRouteImport } from './routes/account.soumissions_.$id'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenariatRoute = PartenariatRouteImport.update({
  id: '/partenariat',
  path: '/partenariat',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributorRoute = ContributorRouteImport.update({
  id: '/contributor',
  path: '/contributor',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsRoute = ConditionsRouteImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const EpreuvesIdRoute = EpreuvesIdRouteImport.update({
  id: '/epreuves/$id',
  path: '/epreuves/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AccountSoumissionsRoute = AccountSoumissionsRouteImport.update({
  id: '/soumissions',
  path: '/soumissions',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfilRoute = AccountProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AccountRoute,
} as any)
const AccountPortefeuilleRoute = AccountPortefeuilleRouteImport.update({
  id: '/portefeuille',
  path: '/portefeuille',
  getParentRoute: () => AccountRoute,
} as any)
const AccountFavorisRoute = AccountFavorisRouteImport.update({
  id: '/favoris',
  path: '/favoris',
  getParentRoute: () => AccountRoute,
} as any)
const AccountBibliothequeRoute = AccountBibliothequeRouteImport.update({
  id: '/bibliotheque',
  path: '/bibliotheque',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSoumissionsIdRoute = AccountSoumissionsIdRouteImport.update({
  id: '/soumissions_/$id',
  path: '/soumissions/$id',
  getParentRoute: () => AccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/conditions': typeof ConditionsRoute
  '/contact': typeof ContactRoute
  '/contributor': typeof ContributorRoute
  '/docs': typeof DocsRoute
  '/faq': typeof FaqRoute
  '/partenariat': typeof PartenariatRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/account/bibliotheque': typeof AccountBibliothequeRoute
  '/account/favoris': typeof AccountFavorisRoute
  '/account/portefeuille': typeof AccountPortefeuilleRoute
  '/account/profil': typeof AccountProfilRoute
  '/account/soumissions': typeof AccountSoumissionsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/epreuves/$id': typeof EpreuvesIdRoute
  '/account/': typeof AccountIndexRoute
  '/account/soumissions/$id': typeof AccountSoumissionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/conditions': typeof ConditionsRoute
  '/contact': typeof ContactRoute
  '/contributor': typeof ContributorRoute
  '/docs': typeof DocsRoute
  '/faq': typeof FaqRoute
  '/partenariat': typeof PartenariatRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/account/bibliotheque': typeof AccountBibliothequeRoute
  '/account/favoris': typeof AccountFavorisRoute
  '/account/portefeuille': typeof AccountPortefeuilleRoute
  '/account/profil': typeof AccountProfilRoute
  '/account/soumissions': typeof AccountSoumissionsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/epreuves/$id': typeof EpreuvesIdRoute
  '/account': typeof AccountIndexRoute
  '/account/soumissions/$id': typeof AccountSoumissionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/conditions': typeof ConditionsRoute
  '/contact': typeof ContactRoute
  '/contributor': typeof ContributorRoute
  '/docs': typeof DocsRoute
  '/faq': typeof FaqRoute
  '/partenariat': typeof PartenariatRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/account/bibliotheque': typeof AccountBibliothequeRoute
  '/account/favoris': typeof AccountFavorisRoute
  '/account/portefeuille': typeof AccountPortefeuilleRoute
  '/account/profil': typeof AccountProfilRoute
  '/account/soumissions': typeof AccountSoumissionsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/epreuves/$id': typeof EpreuvesIdRoute
  '/account/': typeof AccountIndexRoute
  '/account/soumissions_/$id': typeof AccountSoumissionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/conditions'
    | '/contact'
    | '/contributor'
    | '/docs'
    | '/faq'
    | '/partenariat'
    | '/sitemap.xml'
    | '/submit'
    | '/account/bibliotheque'
    | '/account/favoris'
    | '/account/portefeuille'
    | '/account/profil'
    | '/account/soumissions'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/epreuves/$id'
    | '/account/'
    | '/account/soumissions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/conditions'
    | '/contact'
    | '/contributor'
    | '/docs'
    | '/faq'
    | '/partenariat'
    | '/sitemap.xml'
    | '/submit'
    | '/account/bibliotheque'
    | '/account/favoris'
    | '/account/portefeuille'
    | '/account/profil'
    | '/account/soumissions'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/epreuves/$id'
    | '/account'
    | '/account/soumissions/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/conditions'
    | '/contact'
    | '/contributor'
    | '/docs'
    | '/faq'
    | '/partenariat'
    | '/sitemap.xml'
    | '/submit'
    | '/account/bibliotheque'
    | '/account/favoris'
    | '/account/portefeuille'
    | '/account/profil'
    | '/account/soumissions'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/epreuves/$id'
    | '/account/'
    | '/account/soumissions_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRouteWithChildren
  ConditionsRoute: typeof ConditionsRoute
  ContactRoute: typeof ContactRoute
  ContributorRoute: typeof ContributorRoute
  DocsRoute: typeof DocsRoute
  FaqRoute: typeof FaqRoute
  PartenariatRoute: typeof PartenariatRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubmitRoute: typeof SubmitRoute
  EpreuvesIdRoute: typeof EpreuvesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenariat': {
      id: '/partenariat'
      path: '/partenariat'
      fullPath: '/partenariat'
      preLoaderRoute: typeof PartenariatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributor': {
      id: '/contributor'
      path: '/contributor'
      fullPath: '/contributor'
      preLoaderRoute: typeof ContributorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions': {
      id: '/conditions'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof ConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/epreuves/$id': {
      id: '/epreuves/$id'
      path: '/epreuves/$id'
      fullPath: '/epreuves/$id'
      preLoaderRoute: typeof EpreuvesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/account/soumissions': {
      id: '/account/soumissions'
      path: '/soumissions'
      fullPath: '/account/soumissions'
      preLoaderRoute: typeof AccountSoumissionsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profil': {
      id: '/account/profil'
      path: '/profil'
      fullPath: '/account/profil'
      preLoaderRoute: typeof AccountProfilRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/portefeuille': {
      id: '/account/portefeuille'
      path: '/portefeuille'
      fullPath: '/account/portefeuille'
      preLoaderRoute: typeof AccountPortefeuilleRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/favoris': {
      id: '/account/favoris'
      path: '/favoris'
      fullPath: '/account/favoris'
      preLoaderRoute: typeof AccountFavorisRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/bibliotheque': {
      id: '/account/bibliotheque'
      path: '/bibliotheque'
      fullPath: '/account/bibliotheque'
      preLoaderRoute: typeof AccountBibliothequeRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/soumissions_/$id': {
      id: '/account/soumissions_/$id'
      path: '/soumissions/$id'
      fullPath: '/account/soumissions/$id'
      preLoaderRoute: typeof AccountSoumissionsIdRouteImport
      parentRoute: typeof AccountRoute
    }
  }
}

interface AccountRouteChildren {
  AccountBibliothequeRoute: typeof AccountBibliothequeRoute
  AccountFavorisRoute: typeof AccountFavorisRoute
  AccountPortefeuilleRoute: typeof AccountPortefeuilleRoute
  AccountProfilRoute: typeof AccountProfilRoute
  AccountSoumissionsRoute: typeof AccountSoumissionsRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountSoumissionsIdRoute: typeof AccountSoumissionsIdRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountBibliothequeRoute: AccountBibliothequeRoute,
  AccountFavorisRoute: AccountFavorisRoute,
  AccountPortefeuilleRoute: AccountPortefeuilleRoute,
  AccountProfilRoute: AccountProfilRoute,
  AccountSoumissionsRoute: AccountSoumissionsRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountSoumissionsIdRoute: AccountSoumissionsIdRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRouteWithChildren,
  ConditionsRoute: ConditionsRoute,
  ContactRoute: ContactRoute,
  ContributorRoute: ContributorRoute,
  DocsRoute: DocsRoute,
  FaqRoute: FaqRoute,
  PartenariatRoute: PartenariatRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubmitRoute: SubmitRoute,
  EpreuvesIdRoute: EpreuvesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
